import './scss/globals.scss'
import { Lato } from 'next/font/google'
import Header from './components/Header'

const lato = Lato({ 
  weight:['400', '700', '900',],
  subsets: ['latin'] }
  )

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'full stack developer & iOS'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
      <Header />
      <main>{children}</main>
        </body>
    </html>
  )
}
